version: '3.7'

services:
  web:
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/code/
    ports:
      - 8000:8000
    env_file:
      - ./.docker-env
    depends_on:
      - db
  db:
    image: postgres:12.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.docker-env
    ports:
      - "5434:5432"

volumes:
  postgres_data:

